name: TownyConstructionSet
main: crehop.Main
version: 1.0
description: By Crehop!
commands:
  build:
    description: Use it to build!
    aliases: [lib]
    
permissions:
  constructor.admin:
    description: Gives access to all Admin commands!
    default: op
  
